db.url=jdbc:mysql://3WgSn71QQpx52CN.root:OOTja2VZRm0d3WkQ@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/auction_db?sslMode=VERIFY_IDENTITY
db.user=3WgSn71QQpx52CN.root
db.password=OOTja2VZRm0d3WkQ
db.driver=com.mysql.cj.jdbc.Driver